SUBROUTINE REALWIND(SIG)
INTEGER :: SIG

IF (FL_WD_ON == 0) RETURN
IF (FL_RL_WD == 1) RETURN
  SELECT CASE (SIG)
  CASE(0)
    CALL REALWIND_INITIAL("../DATA/ERA40","E-WSS","2002","6hr","./",I0,XDEG,J0,YDEG,WINDID)
  CASE(1)
    IF (MOD(4*ITF,ITFDAY).EQ.0) THEN
        II=ITF*4/ITFDAY+1
        CALL REALWIND_INFLOW(windid,II,I0,J0,taux,I1,J1)
    ENDIF
  CASE DEFAULT
    WRITE(6,*)"WRONG REALWIND SIGNAL"
    WRITE(FNO_LOG,*)"WRONG REALWIND SIGNAL"
  END SELECT
END SUBROUTINE REALWIND

