SUBROUTINE TURBULENCE(SIG)
  INTEGER :: SIG

  IF ( DIMEN == 2 ) RETURN
  SELECT CASE (SIG)
  CASE(0)
    CALL PP82
  CASE(1)
    WRITE(*,*)"NOT SUPPORT IN THIS VERSION"
  CASE(2)
    WRITE(*,*)"NOT SUPPORT IN THIS VERSION"
  CASE DEFAULT
    WRITE(6,*)"WRONG TURBULENCE TYPE"
    WRITE(FNO_LOG,*)"WRONG TURBULENCE TYPE"
  END SELECT
END SUBROUTINE TURBULENCE 

